import type { SiteContent } from '@/lib/types';

export const defaultSiteContent: Omit<SiteContent, 'id' | 'updated_at'> = {
  brand_name: 'Congepan',
  headline: 'O segredo das melhores padarias está aqui.',
  subheadline: 'Pães congelados com qualidade, praticidade e atendimento rápido para sua padaria vender mais todos os dias.',
  whatsapp_number: '5585999999999',
  whatsapp_message: 'Olá! Vim pelo site da Congepan e quero falar com a equipe.',
  hero_logo_url: '/congepan-logo.png',
  banner_1_url: '/congepan-banner-1.png',
  banner_2_url: '/congepan-banner-2.png',
  banner_3_url: '/congepan-banner-3.png',
  primary_color: '#28411f',
  secondary_color: '#c7841e',
  accent_color: '#0f7a3f',
  bullet_1: 'Mais de 10 anos de experiência',
  bullet_2: 'Pães congelados com qualidade superior',
  bullet_3: 'Atendimento personalizado para sua padaria',
  card_1_title: 'Tradicionais',
  card_1_text: 'Pães clássicos para o dia a dia com padrão e praticidade.',
  card_2_title: 'Linha Extra',
  card_2_text: 'Mais variedade para padarias que querem encantar o cliente.',
  card_3_title: 'Faça Já Seu Pedido',
  card_3_text: 'Entre em contato agora mesmo e fale direto no WhatsApp.',
  about_title: 'Pão, Propósito e Paixão',
  about_text: 'Na Congepan, oferecemos pães congelados de alta qualidade, prontos para assar, garantindo praticidade, rendimento e sabor irresistível para a sua padaria.',
  cta_title: 'Fale Conosco',
  cta_text: 'Estamos prontos para atender você e levar mais praticidade para sua produção.',
  cta_button_text: 'Fale pelo WhatsApp',
  footer_text: '© 2026 Congepan - Qualidade e Praticidade na sua Padaria. Todos os direitos reservados.',
  privacy_policy_text: 'Este site pode registrar endereço IP, cidade aproximada, dispositivo e dados básicos de navegação para fins de segurança, estatística e controle interno. Essas informações não são utilizadas para fins irregulares e são tratadas de forma restrita.'
};
