export type SiteContent = {
  id: number;
  brand_name: string;
  headline: string;
  subheadline: string;
  whatsapp_number: string;
  whatsapp_message: string;
  hero_logo_url: string | null;
  banner_1_url: string | null;
  banner_2_url: string | null;
  banner_3_url: string | null;
  primary_color: string;
  secondary_color: string;
  accent_color: string;
  bullet_1: string;
  bullet_2: string;
  bullet_3: string;
  card_1_title: string;
  card_1_text: string;
  card_2_title: string;
  card_2_text: string;
  card_3_title: string;
  card_3_text: string;
  about_title: string;
  about_text: string;
  cta_title: string;
  cta_text: string;
  cta_button_text: string;
  footer_text: string;
  privacy_policy_text: string;
  // Vídeos
  video_1_url: string | null;
  video_1_title: string;
  video_1_description: string;
  video_1_visible: boolean;
  video_2_url: string | null;
  video_2_title: string;
  video_2_description: string;
  video_2_visible: boolean;
  video_3_url: string | null;
  video_3_title: string;
  video_3_description: string;
  video_3_visible: boolean;
  // Visibilidade de seções
  section_cards_visible: boolean;
  section_about_visible: boolean;
  section_videos_visible: boolean;
  section_cta_visible: boolean;
  updated_at: string;
};

export type VisitRecord = {
  id: number;
  created_at: string;
  page_path: string;
  ip_address: string | null;
  city: string | null;
  region: string | null;
  country: string | null;
  latitude: string | null;
  longitude: string | null;
  referer: string | null;
  user_agent: string | null;
  device_type: string | null;
};
